name: 'Thank You Action'
description: 'Say Thank You for new Pull Request'
author: 'Sanjali Nagare'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
  TENOR_TOKEN:
    description: 'Tenor API token'
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'